--------------------------------------------------------
--  File created - Montag-Juni-10-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type ADRESSET
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "DEM2"."ADRESSET" AS OBJECT 
( 
    ort VARCHAR2(50),
    plz VARCHAR2(5),
    strasse VARCHAR2(50),
    hausnummer VARCHAR2(10),
    adresszusatz VARCHAR2(50)
/* TODO enter attribute and method declarations here */ 
)



/
--------------------------------------------------------
--  DDL for Type NAMET
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "DEM2"."NAMET" AS OBJECT (
    nachname VARCHAR2(50),
    vorname VARCHAR2(50)
);



/
--------------------------------------------------------
--  DDL for Type ZAHLUNGSINFORMATIONENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "DEM2"."ZAHLUNGSINFORMATIONENT" AS OBJECT (
    art VARCHAR2(30),
    kontoinhaber VARCHAR2(50),
    iBAN_Kontonummer VARCHAR2(34) --Maximall?nge nach Wikipedia
);



/
--------------------------------------------------------
--  DDL for Table ARBEITSSCHRITT
--------------------------------------------------------

  CREATE TABLE "DEM2"."ARBEITSSCHRITT" 
   (	"ARBEITSSCHRITT_ID" NUMBER(*,0), 
	"DAUER_MIN" NUMBER(*,0), 
	"QUALIFIKATION" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"ANZAHL_MITARBEITER" NUMBER(*,0), 
	"TECHNIK_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table BAND
--------------------------------------------------------

  CREATE TABLE "DEM2"."BAND" 
   (	"BAND_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ADRESSE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"GROESSE_DER_BAND" NUMBER(*,0), 
	"PERSON_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table BEWERTUNG
--------------------------------------------------------

  CREATE TABLE "DEM2"."BEWERTUNG" 
   (	"BEWERTUNG_ID" NUMBER(*,0), 
	"BEWERTUNG" NUMBER(*,0), 
	"VERFASSUNGSDATUM" DATE, 
	"KUNDE_ID" NUMBER(*,0), 
	"EVENT_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table BUCHUNG
--------------------------------------------------------

  CREATE TABLE "DEM2"."BUCHUNG" 
   (	"BUCHUNG_ID" NUMBER(*,0), 
	"DATUM" DATE, 
	"KUNDE_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table BUCHUNGSPOSITION
--------------------------------------------------------

  CREATE TABLE "DEM2"."BUCHUNGSPOSITION" 
   (	"POSITIONS_NUMMER" NUMBER(*,0), 
	"BEZEICHNUNG" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ANZAHL" NUMBER(*,0), 
	"BUCHUNG_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table EINSATZ
--------------------------------------------------------

  CREATE TABLE "DEM2"."EINSATZ" 
   (	"EINSATZ_ID" NUMBER(*,0), 
	"DATUM" DATE, 
	"RESSOURCE_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "DEM2"."EVENT" 
   (	"EVENT_ID" NUMBER(*,0), 
	"TITEL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DATUM_ANFANG" DATE, 
	"JETZT_AUF_WEBSITE" NUMBER(*,0), 
	"WEBSITE_AUFRUFE_24H" NUMBER(*,0), 
	"LOCATION_ID" NUMBER(*,0), 
	"EVENTKATEGORIE_ID" NUMBER(*,0), 
	"DAUER_STD" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table EVENTKATEGORIE
--------------------------------------------------------

  CREATE TABLE "DEM2"."EVENTKATEGORIE" 
   (	"EVENTKATEGORIE_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"BESCHREIBUNG" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table EVENT_BAND
--------------------------------------------------------

  CREATE TABLE "DEM2"."EVENT_BAND" 
   (	"EVENT_ID" NUMBER(*,0), 
	"BAND_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table KUNDE
--------------------------------------------------------

  CREATE TABLE "DEM2"."KUNDE" 
   (	"KUNDE_ID" NUMBER(*,0), 
	"ALTER_PERSON" NUMBER(*,0), 
	"EMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TELEFONNUMMER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"VORNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NACHNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ZAHLUNGSINFORMATIONEN" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ADRESSE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "DEM2"."LOCATION" 
   (	"LOCATION_ID" NUMBER(*,0), 
	"ANZAHL_SITZPLAETZE" NUMBER(*,0), 
	"ANZAHL_STEHPLAETZE" NUMBER(*,0), 
	"ADRESSE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"BARRIEREFREI" CHAR(5 BYTE) COLLATE "USING_NLS_COMP", 
	"PERSON_ID" NUMBER(*,0), 
	"BEZEICHNUNG" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table MITARBEITER
--------------------------------------------------------

  CREATE TABLE "DEM2"."MITARBEITER" 
   (	"MITARBEITER_ID" NUMBER(*,0), 
	"VORNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ADRESSE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PERSON_ALTER" NUMBER(*,0), 
	"EMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TELEFONNUMMER" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ZAHLUNGSINFORMATIONEN" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"QUALIFIKATION" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"GEHALT" NUMBER(*,0), 
	"MAX_ARBEITSPENSUM_WOCHE" NUMBER(*,0), 
	"NACHNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "DEM2"."PERSON" 
   (	"PERSON_ID" NUMBER(*,0), 
	"VORNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PERSON_ALTER" NUMBER(*,0), 
	"EMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TELEFONNUMMER" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ADRESSE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NACHNAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table RESSOURCE
--------------------------------------------------------

  CREATE TABLE "DEM2"."RESSOURCE" 
   (	"RESSOURCE_ID" NUMBER(*,0), 
	"MITARBEITER_ID" NUMBER(*,0), 
	"TECHNIK_ID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TECHNIK
--------------------------------------------------------

  CREATE TABLE "DEM2"."TECHNIK" 
   (	"TECHNIK_ID" NUMBER(*,0), 
	"KATEGORIE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MODELL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"KOSTEN" NUMBER(*,0), 
	"BETRIEBSKOSTEN_STD" NUMBER(*,0), 
	"MIETKOSTEN_TAG" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "DEM2"."TICKET" 
   (	"TICKET_ID" NUMBER(*,0), 
	"PLATZ_NUMMER" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"PREIS" FLOAT(126), 
	"PLATZART" VARCHAR2(25 BYTE) COLLATE "USING_NLS_COMP", 
	"ERMAESSIGT" CHAR(5 BYTE) COLLATE "USING_NLS_COMP", 
	"EVENT_ID" NUMBER(*,0), 
	"BUCHUNGSPOSITION_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for View MANAGERB003
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEM2"."MANAGERB003" ("STAFFNO", "FNAME", "LNAME", "POSITION", "GENDER", "DOB", "SALARY", "BRANCHNO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select "STAFFNO","FNAME","LNAME","POSITION","GENDER","DOB","SALARY","BRANCHNO"
from STAFF
where branchno='B003'
;
--------------------------------------------------------
--  DDL for View STAFFB003
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEM2"."STAFFB003" ("STAFFNO", "FNAME", "LNAME", "POSITION") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select staffno, fname, lname, position
from staff
where branchno='B003'
;
--------------------------------------------------------
--  DDL for Index BUCHUNG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."BUCHUNG_PK" ON "DEM2"."BUCHUNG" ("BUCHUNG_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index EVENTKATEGORIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."EVENTKATEGORIE_PK" ON "DEM2"."EVENTKATEGORIE" ("EVENTKATEGORIE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."LOCATION_PK" ON "DEM2"."LOCATION" ("LOCATION_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index BEWERTUNG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."BEWERTUNG_PK" ON "DEM2"."BEWERTUNG" ("BEWERTUNG_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index EINSATZ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."EINSATZ_PK" ON "DEM2"."EINSATZ" ("EINSATZ_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index ARBEITSSCHRITTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."ARBEITSSCHRITTE_PK" ON "DEM2"."ARBEITSSCHRITT" ("ARBEITSSCHRITT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index BAND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."BAND_PK" ON "DEM2"."BAND" ("BAND_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index KUNDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."KUNDE_PK" ON "DEM2"."KUNDE" ("KUNDE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."PERSON_PK" ON "DEM2"."PERSON" ("PERSON_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index BUCHUNGSPOSITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."BUCHUNGSPOSITION_PK" ON "DEM2"."BUCHUNGSPOSITION" ("POSITIONS_NUMMER") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index TECHNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."TECHNIK_PK" ON "DEM2"."TECHNIK" ("TECHNIK_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."TICKET_PK" ON "DEM2"."TICKET" ("TICKET_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index EVENT_BAND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."EVENT_BAND_PK" ON "DEM2"."EVENT_BAND" ("EVENT_ID", "BAND_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index RESSOURCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."RESSOURCE_PK" ON "DEM2"."RESSOURCE" ("RESSOURCE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index MITARBEITER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."MITARBEITER_PK" ON "DEM2"."MITARBEITER" ("MITARBEITER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEM2"."EVENT_PK" ON "DEM2"."EVENT" ("EVENT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table BUCHUNGSPOSITION
--------------------------------------------------------

  ALTER TABLE "DEM2"."BUCHUNGSPOSITION" MODIFY ("POSITIONS_NUMMER" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BUCHUNGSPOSITION" MODIFY ("BEZEICHNUNG" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BUCHUNGSPOSITION" MODIFY ("ANZAHL" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BUCHUNGSPOSITION" ADD CONSTRAINT "BUCHUNGSPOSITION_PK" PRIMARY KEY ("POSITIONS_NUMMER")
  USING INDEX "DEM2"."BUCHUNGSPOSITION_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENTKATEGORIE
--------------------------------------------------------

  ALTER TABLE "DEM2"."EVENTKATEGORIE" MODIFY ("EVENTKATEGORIE_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EVENTKATEGORIE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EVENTKATEGORIE" MODIFY ("BESCHREIBUNG" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EVENTKATEGORIE" ADD CONSTRAINT "EVENTKATEGORIE_PK" PRIMARY KEY ("EVENTKATEGORIE_ID")
  USING INDEX "DEM2"."EVENTKATEGORIE_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUCHUNG
--------------------------------------------------------

  ALTER TABLE "DEM2"."BUCHUNG" MODIFY ("BUCHUNG_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BUCHUNG" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BUCHUNG" ADD CONSTRAINT "BUCHUNG_PK" PRIMARY KEY ("BUCHUNG_ID")
  USING INDEX "DEM2"."BUCHUNG_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TECHNIK
--------------------------------------------------------

  ALTER TABLE "DEM2"."TECHNIK" MODIFY ("TECHNIK_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TECHNIK" MODIFY ("KATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TECHNIK" MODIFY ("MODELL" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TECHNIK" MODIFY ("KOSTEN" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TECHNIK" MODIFY ("BETRIEBSKOSTEN_STD" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TECHNIK" MODIFY ("MIETKOSTEN_TAG" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TECHNIK" ADD CONSTRAINT "TECHNIK_PK" PRIMARY KEY ("TECHNIK_ID")
  USING INDEX "DEM2"."TECHNIK_PK"  ENABLE;
  ALTER TABLE "DEM2"."TECHNIK" ADD CONSTRAINT "TECHNIK_CHK1" CHECK (kategorie IN ('Schall','Licht','Buehne','Stromerzeugung und Verteilung','Zaeune und Absperrungen','Instrumente','Pyrotechnik','Ueberdachung','Sonstiges')) ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "DEM2"."EVENT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EVENT" MODIFY ("TITEL" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX "DEM2"."EVENT_PK"  ENABLE;
  ALTER TABLE "DEM2"."EVENT" MODIFY ("DATUM_ANFANG" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EVENT" MODIFY ("DAUER_STD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESSOURCE
--------------------------------------------------------

  ALTER TABLE "DEM2"."RESSOURCE" MODIFY ("RESSOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."RESSOURCE" ADD CONSTRAINT "RESSOURCE_PK" PRIMARY KEY ("RESSOURCE_ID")
  USING INDEX "DEM2"."RESSOURCE_PK"  ENABLE;
  ALTER TABLE "DEM2"."RESSOURCE" ADD CONSTRAINT "RESSOURCE_CHK1" CHECK ((mitarbeiter_id IS NOT NULL AND technik_id IS NULL) OR (mitarbeiter_id IS NULL AND technik_id IS NOT NULL)) ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "DEM2"."PERSON" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."PERSON" MODIFY ("PERSON_ALTER" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."PERSON" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."PERSON" MODIFY ("TELEFONNUMMER" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("PERSON_ID")
  USING INDEX "DEM2"."PERSON_PK"  ENABLE;
  ALTER TABLE "DEM2"."PERSON" MODIFY ("NACHNAME" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."PERSON" MODIFY ("VORNAME" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."PERSON" MODIFY ("ADRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENT_BAND
--------------------------------------------------------

  ALTER TABLE "DEM2"."EVENT_BAND" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EVENT_BAND" MODIFY ("BAND_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EVENT_BAND" ADD CONSTRAINT "EVENT_BAND_PK" PRIMARY KEY ("EVENT_ID", "BAND_ID")
  USING INDEX "DEM2"."EVENT_BAND_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BEWERTUNG
--------------------------------------------------------

  ALTER TABLE "DEM2"."BEWERTUNG" MODIFY ("BEWERTUNG_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BEWERTUNG" MODIFY ("BEWERTUNG" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BEWERTUNG" MODIFY ("VERFASSUNGSDATUM" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BEWERTUNG" ADD CONSTRAINT "BEWERTUNG_PK" PRIMARY KEY ("BEWERTUNG_ID")
  USING INDEX "DEM2"."BEWERTUNG_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KUNDE
--------------------------------------------------------

  ALTER TABLE "DEM2"."KUNDE" MODIFY ("VORNAME" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."KUNDE" MODIFY ("KUNDE_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."KUNDE" MODIFY ("ALTER_PERSON" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."KUNDE" MODIFY ("NACHNAME" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."KUNDE" MODIFY ("ZAHLUNGSINFORMATIONEN" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."KUNDE" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."KUNDE" ADD CONSTRAINT "KUNDE_PK" PRIMARY KEY ("KUNDE_ID")
  USING INDEX "DEM2"."KUNDE_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MITARBEITER
--------------------------------------------------------

  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("MITARBEITER_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("VORNAME" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("PERSON_ALTER" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("TELEFONNUMMER" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("ZAHLUNGSINFORMATIONEN" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("QUALIFIKATION" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("GEHALT" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("MAX_ARBEITSPENSUM_WOCHE" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" ADD CONSTRAINT "MITARBEITER_PK" PRIMARY KEY ("MITARBEITER_ID")
  USING INDEX "DEM2"."MITARBEITER_PK"  ENABLE;
  ALTER TABLE "DEM2"."MITARBEITER" MODIFY ("NACHNAME" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."MITARBEITER" ADD CONSTRAINT "MITARBEITER_CHK1" CHECK ("QUALIFIKATION"='Buehnentechnik' OR "QUALIFIKATION"='Lichttechnik' OR "QUALIFIKATION"='Videotechnik' OR "QUALIFIKATION"='Backlinetechnik' OR "QUALIFIKATION"='Pyrotechnik' OR "QUALIFIKATION"='Sicherheitstechnik' OR "QUALIFIKATION"='Einlasskontrolle' OR "QUALIFIKATION"='Ersthelfer' OR "QUALIFIKATION"='Crowd Controll' OR "QUALIFIKATION"='Catering' OR "QUALIFIKATION"='Reinigung' OR "QUALIFIKATION"='Public Relations') ENABLE;
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "DEM2"."TICKET" MODIFY ("TICKET_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TICKET" MODIFY ("PLATZ_NUMMER" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TICKET" MODIFY ("PREIS" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TICKET" MODIFY ("PLATZART" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TICKET" MODIFY ("ERMAESSIGT" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("TICKET_ID")
  USING INDEX "DEM2"."TICKET_PK"  ENABLE;
  ALTER TABLE "DEM2"."TICKET" ADD CONSTRAINT "TICKET_CHK1" CHECK (platzart IN ('Stehplatz', 'Sitzplatz Kategorie A', 'Sitzplatz Kategorie B', 'Sitzplatz Kategorie C',  'Sitzplatz Kategorie D',  'Sitzplatz Kategorie E')) ENABLE;
  ALTER TABLE "DEM2"."TICKET" ADD CONSTRAINT "TICKET_CHK2" CHECK (ermaessigt IN ('true', 'false')) ENABLE;
--------------------------------------------------------
--  Constraints for Table ARBEITSSCHRITT
--------------------------------------------------------

  ALTER TABLE "DEM2"."ARBEITSSCHRITT" MODIFY ("ARBEITSSCHRITT_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."ARBEITSSCHRITT" MODIFY ("DAUER_MIN" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."ARBEITSSCHRITT" MODIFY ("QUALIFIKATION" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."ARBEITSSCHRITT" MODIFY ("ANZAHL_MITARBEITER" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."ARBEITSSCHRITT" ADD CONSTRAINT "ARBEITSSCHRITTE_PK" PRIMARY KEY ("ARBEITSSCHRITT_ID")
  USING INDEX "DEM2"."ARBEITSSCHRITTE_PK"  ENABLE;
  ALTER TABLE "DEM2"."ARBEITSSCHRITT" ADD CONSTRAINT "ARBEITSSCHRITT_CHK1" CHECK (qualifikation IN ('Buehnentechnik','Lichttechnik','Videotechnik','Backlinetechnik','Pyrotechnik','Sicherheitstechnik','Einlasskontrolle','Ersthelfer','Crowd Controll','Catering','Reinigung','Public Relations')) ENABLE;
--------------------------------------------------------
--  Constraints for Table EINSATZ
--------------------------------------------------------

  ALTER TABLE "DEM2"."EINSATZ" MODIFY ("EINSATZ_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EINSATZ" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EINSATZ" MODIFY ("RESSOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."EINSATZ" ADD CONSTRAINT "EINSATZ_PK" PRIMARY KEY ("EINSATZ_ID")
  USING INDEX "DEM2"."EINSATZ_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BAND
--------------------------------------------------------

  ALTER TABLE "DEM2"."BAND" MODIFY ("BAND_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BAND" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BAND" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BAND" MODIFY ("GROESSE_DER_BAND" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."BAND" ADD CONSTRAINT "BAND_PK" PRIMARY KEY ("BAND_ID")
  USING INDEX "DEM2"."BAND_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "DEM2"."LOCATION" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."LOCATION" MODIFY ("ANZAHL_SITZPLAETZE" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."LOCATION" MODIFY ("ANZAHL_STEHPLAETZE" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."LOCATION" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."LOCATION" MODIFY ("BARRIEREFREI" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."LOCATION" MODIFY ("BEZEICHNUNG" NOT NULL ENABLE);
  ALTER TABLE "DEM2"."LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("LOCATION_ID")
  USING INDEX "DEM2"."LOCATION_PK"  ENABLE;
  ALTER TABLE "DEM2"."LOCATION" ADD CONSTRAINT "LOCATION_CHK1" CHECK (barrierefrei IN ('true', 'false')) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARBEITSSCHRITT
--------------------------------------------------------

  ALTER TABLE "DEM2"."ARBEITSSCHRITT" ADD CONSTRAINT "ARBEITSSCHRITT_FK1" FOREIGN KEY ("TECHNIK_ID")
	  REFERENCES "DEM2"."TECHNIK" ("TECHNIK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BAND
--------------------------------------------------------

  ALTER TABLE "DEM2"."BAND" ADD CONSTRAINT "BAND_FK1" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "DEM2"."PERSON" ("PERSON_ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table BEWERTUNG
--------------------------------------------------------

  ALTER TABLE "DEM2"."BEWERTUNG" ADD CONSTRAINT "BEWERTUNG_FK1" FOREIGN KEY ("KUNDE_ID")
	  REFERENCES "DEM2"."KUNDE" ("KUNDE_ID") DISABLE;
  ALTER TABLE "DEM2"."BEWERTUNG" ADD CONSTRAINT "BEWERTUNG_FK2" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "DEM2"."EVENT" ("EVENT_ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUCHUNG
--------------------------------------------------------

  ALTER TABLE "DEM2"."BUCHUNG" ADD CONSTRAINT "BUCHUNG_FK1" FOREIGN KEY ("KUNDE_ID")
	  REFERENCES "DEM2"."KUNDE" ("KUNDE_ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUCHUNGSPOSITION
--------------------------------------------------------

  ALTER TABLE "DEM2"."BUCHUNGSPOSITION" ADD CONSTRAINT "BUCHUNGSPOSITION_FK1" FOREIGN KEY ("BUCHUNG_ID")
	  REFERENCES "DEM2"."BUCHUNG" ("BUCHUNG_ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table EINSATZ
--------------------------------------------------------

  ALTER TABLE "DEM2"."EINSATZ" ADD CONSTRAINT "EINSATZ_FK1" FOREIGN KEY ("RESSOURCE_ID")
	  REFERENCES "DEM2"."RESSOURCE" ("RESSOURCE_ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "DEM2"."EVENT" ADD CONSTRAINT "EVENT_FK1" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "DEM2"."LOCATION" ("LOCATION_ID") DISABLE;
  ALTER TABLE "DEM2"."EVENT" ADD CONSTRAINT "EVENT_FK2" FOREIGN KEY ("EVENTKATEGORIE_ID")
	  REFERENCES "DEM2"."EVENTKATEGORIE" ("EVENTKATEGORIE_ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT_BAND
--------------------------------------------------------

  ALTER TABLE "DEM2"."EVENT_BAND" ADD CONSTRAINT "EVENT_BAND_FK1" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "DEM2"."EVENT" ("EVENT_ID") DISABLE;
  ALTER TABLE "DEM2"."EVENT_BAND" ADD CONSTRAINT "EVENT_BAND_FK2" FOREIGN KEY ("BAND_ID")
	  REFERENCES "DEM2"."BAND" ("BAND_ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "DEM2"."LOCATION" ADD CONSTRAINT "LOCATION_FK1" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "DEM2"."PERSON" ("PERSON_ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESSOURCE
--------------------------------------------------------

  ALTER TABLE "DEM2"."RESSOURCE" ADD CONSTRAINT "RESSOURCE_FK1" FOREIGN KEY ("MITARBEITER_ID")
	  REFERENCES "DEM2"."MITARBEITER" ("MITARBEITER_ID") DISABLE;
  ALTER TABLE "DEM2"."RESSOURCE" ADD CONSTRAINT "RESSOURCE_FK2" FOREIGN KEY ("TECHNIK_ID")
	  REFERENCES "DEM2"."TECHNIK" ("TECHNIK_ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "DEM2"."TICKET" ADD CONSTRAINT "TICKET_FK1" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "DEM2"."EVENT" ("EVENT_ID") DISABLE;
  ALTER TABLE "DEM2"."TICKET" ADD CONSTRAINT "TICKET_FK2" FOREIGN KEY ("BUCHUNGSPOSITION_ID")
	  REFERENCES "DEM2"."BUCHUNGSPOSITION" ("POSITIONS_NUMMER") DISABLE;
