
--Daten für Table "TECHNIK"
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('1', 'Licht', 'StratoTech 2000', '1494', '186', '555');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('2', 'Licht', 'ZenithTech X9', '849', '163', '725');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('3', 'Stromerzeugung & Verteilung', 'VertexDrive 700', '2462', '140', '264');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('4', 'Schall', 'DeltaDrive X1', '5353', '45', '167');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('5', 'Schall', 'HexaTech 5000', '4888', '150', '236');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('6', 'Licht', 'QuantumEdge X9', '1470', '85', '642');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('7', 'Sonstiges', 'AlphaCore V7', '4083', '152', '741');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('8', 'Überdachung', 'SyncCore 800', '750', '93', '687');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('9', 'Bühne', 'Magnetron 6000', '2561', '47', '911');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('10', 'Licht', 'PowerWave 100', '8073', '171', '755');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('11', 'Instrumente', 'TechSync V1', '1147', '161', '441');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('12', 'Schall', 'HyperDrive T2', '710', '58', '477');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('13', 'Bühne', 'PowerTrack T2', '2123', '75', '643');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('14', 'Bühne', 'TechSync V1', '6028', '133', '229');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('15', 'Sonstiges', 'VertexDrive 700', '9511', '76', '400');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('16', 'Licht', 'TechWave Z8', '1440', '170', '277');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('17', 'Stromerzeugung & Verteilung', 'EcoSync 700', '7313', '190', '476');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('18', 'Zäune & Absperrungen', 'ZenithTech X9', '8709', '26', '354');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('19', 'Licht', 'OptiTech G4', '8825', '183', '972');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('20', 'Sonstiges', 'HexaSync 1000', '1852', '195', '232');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('21', 'Überdachung', 'SyncDrive T8', '6251', '91', '397');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('22', 'Schall', 'CyberPulse 1000', '2879', '145', '993');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('23', 'Stromerzeugung & Verteilung', 'VelocityTech V3', '6827', '169', '707');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('24', 'Sonstiges', 'PowerTrack T2', '1386', '186', '291');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('25', 'Zäune & Absperrungen', 'NanoPulse T4', '4250', '194', '170');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('26', 'Zäune & Absperrungen', 'AlphaWave Z10', '8781', '126', '483');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('27', 'Schall', 'TechSync 2000', '9869', '33', '274');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('28', 'Schall', 'VertexX 4500', '4089', '76', '446');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('29', 'Licht', 'OmniDrive 300', '8826', '92', '588');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('30', 'Zäune & Absperrungen', 'StratoMax X5', '8864', '139', '529');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('31', 'Licht', 'EcoPulse X5', '9370', '118', '166');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('32', 'Schall', 'StratoDrive 300', '2283', '23', '734');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('33', 'Licht', 'QuantumDrive 600', '5218', '186', '369');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('34', 'Licht', 'OmegaTrack X2', '8348', '116', '922');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('35', 'Zäune & Absperrungen', 'OptiPulse 350', '4869', '147', '492');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('36', 'Licht', 'MagniFlow 9000', '3986', '118', '490');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('37', 'Zäune & Absperrungen', 'HexaVolt X6', '2548', '116', '544');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('38', 'Instrumente', 'PowerCell Z3', '4502', '186', '502');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('39', 'Bühne', 'PowerTech Z5', '725', '183', '347');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('40', 'Zäune & Absperrungen', 'DeltaCore T4', '7265', '100', '496');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('41', 'Instrumente', 'PowerTech Z5', '7065', '88', '884');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('42', 'Überdachung', 'OptiCore 1500', '6192', '76', '491');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('43', 'Schall', 'OptiTech X7', '6011', '168', '610');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('44', 'Bühne', 'OmniFlex 300', '5166', '63', '938');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('45', 'Stromerzeugung & Verteilung', 'TechWave V2', '8034', '174', '725');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('46', 'Bühne', 'TurboMax X5', '519', '189', '350');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('47', 'Schall', 'OptiWave X1', '4673', '47', '821');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('48', 'Stromerzeugung & Verteilung', 'MagniEdge 100', '8721', '147', '750');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('49', 'Zäune & Absperrungen', 'VelocityTech V3', '7490', '200', '465');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('50', 'Zäune & Absperrungen', 'NanoPulse T4', '2632', '120', '896');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('51', 'Sonstiges', 'TechVolt 500', '1784', '36', '341');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('52', 'Licht', 'HyperCore V1', '2864', '190', '106');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('53', 'Überdachung', 'SyncMaster 100', '2629', '76', '832');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('54', 'Stromerzeugung & Verteilung', 'QuantumTech X8', '5972', '139', '819');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('55', 'Sonstiges', 'OmniPulse Z6', '7144', '190', '343');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('56', 'Zäune & Absperrungen', 'HexaDrive 400', '1670', '138', '363');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('57', 'Sonstiges', 'UltraWave 1500', '3604', '35', '473');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('58', 'Überdachung', 'QuantumEdge X9', '5279', '154', '896');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('59', 'Zäune & Absperrungen', 'OptiWave X1', '4195', '175', '889');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('60', 'Zäune & Absperrungen', 'QuantumCore R4', '4229', '121', '469');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('61', 'Schall', 'UltraSync 800', '749', '76', '388');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('62', 'Licht', 'QuantumDrive Pro', '5265', '188', '323');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('63', 'Überdachung', 'TechVolt 500', '5155', '47', '996');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('64', 'Zäune & Absperrungen', 'TechTrack Z6', '7170', '89', '253');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('65', 'Schall', 'UltraCore 800', '9727', '185', '874');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('66', 'Zäune & Absperrungen', 'HyperTech 700', '9532', '70', '314');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('67', 'Schall', 'HyperFusion 800', '9748', '137', '839');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('68', 'Zäune & Absperrungen', 'InfraEdge Z4', '922', '167', '435');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('69', 'Zäune & Absperrungen', 'MagniVolt 5000', '1326', '59', '553');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('70', 'Licht', 'VertexTech 300', '9870', '115', '718');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('71', 'Stromerzeugung & Verteilung', 'VelocityTech V3', '2046', '84', '953');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('72', 'Schall', 'OptiCore 700', '9906', '177', '462');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('73', 'Bühne', 'ZenithPulse X6', '7997', '147', '192');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('74', 'Zäune & Absperrungen', 'InfraEdge Z4', '3623', '41', '385');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('75', 'Sonstiges', 'VertexTech 300', '2632', '26', '646');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('76', 'Überdachung', 'OmniCore 600', '4117', '73', '851');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('77', 'Bühne', 'HexaDrive 400', '4965', '117', '183');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('78', 'Schall', 'HyperSync Z3', '4500', '24', '448');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('79', 'Sonstiges', 'InfraVolt X4', '4274', '24', '269');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('80', 'Überdachung', 'UltraDrive 800', '6648', '91', '535');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('81', 'Schall', 'HyperWave T1', '1090', '114', '566');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('82', 'Stromerzeugung & Verteilung', 'UltraWave 1500', '7555', '157', '1000');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('83', 'Zäune & Absperrungen', 'NeuroDrive X2', '7503', '99', '203');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('84', 'Schall', 'VertexDrive 700', '3271', '71', '326');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('85', 'Zäune & Absperrungen', 'ZenithPulse X6', '8469', '33', '767');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('86', 'Überdachung', 'TurboTech X9', '8386', '61', '177');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('87', 'Schall', 'ProLink 700', '5027', '174', '383');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('88', 'Bühne', 'NeuroWave Z1', '8653', '169', '806');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('89', 'Bühne', 'StratoMax X5', '8594', '71', '217');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('90', 'Bühne', 'UltraDrive 800', '9212', '116', '685');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('91', 'Zäune & Absperrungen', 'OmegaDrive Z5', '249', '112', '192');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('92', 'Bühne', 'NeuroDrive X2', '2846', '92', '421');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('93', 'Licht', 'OmniPulse Z6', '3417', '87', '342');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('94', 'Licht', 'UltraWave 1500', '3024', '51', '676');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('95', 'Schall', 'VertexTech G5', '7754', '163', '299');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('96', 'Licht', 'VertexDrive 700', '6960', '189', '601');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('97', 'Stromerzeugung & Verteilung', 'TechFlow V3', '8686', '71', '763');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('98', 'Instrumente', 'OmniDrive 300', '5284', '179', '380');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('99', 'Schall', 'OptiCore 700', '4739', '137', '774');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('100', 'Licht', 'VectorGear 2000', '252', '171', '910');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('101', 'Stromerzeugung & Verteilung', 'VertexDrive 700', '7447', '34', '878');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('102', 'Instrumente', 'OmniEdge 900', '6457', '193', '457');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('103', 'Instrumente', 'ProPulse 200', '1626', '130', '507');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('104', 'Licht', 'InfraTech Z5', '5941', '132', '831');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('105', 'Licht', 'QuantumCore R4', '9182', '71', '893');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('106', 'Stromerzeugung & Verteilung', 'HyperDrive T2', '9566', '137', '974');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('107', 'Schall', 'UltraNet 600', '4642', '143', '356');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('108', 'Überdachung', 'OptiTech G4', '3778', '71', '271');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('109', 'Sonstiges', 'HyperSync Z3', '9642', '158', '494');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('110', 'Überdachung', 'NeuroLink Z2', '4010', '57', '470');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('111', 'Pyrotechnik', 'UltraFusion V4', '7547', '21', '565');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('112', 'Licht', 'TechWave V2', '6901', '116', '321');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('113', 'Licht', 'ProtoLink 800', '8924', '172', '857');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('114', 'Instrumente', 'VelocitySync V2', '8613', '98', '197');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('115', 'Licht', 'ProtoLink 800', '8262', '92', '580');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('116', 'Stromerzeugung & Verteilung', 'UltraFlex 700', '5534', '42', '932');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('117', 'Instrumente', 'CyberVolt X4', '4452', '31', '822');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('118', 'Zäune & Absperrungen', 'HexaVolt X6', '6768', '120', '785');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('119', 'Zäune & Absperrungen', 'ZenithCore 200', '1127', '153', '433');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('120', 'Pyrotechnik', 'UltraCore 800', '3407', '195', '217');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('121', 'Schall', 'HexaSync 1000', '9932', '68', '860');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('122', 'Überdachung', 'MagniSync 400', '7754', '56', '135');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('123', 'Schall', 'MagniDrive X4', '5649', '37', '236');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('124', 'Instrumente', 'OptiMax 250', '5236', '96', '746');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('125', 'Stromerzeugung & Verteilung', 'OmegaPulse V2', '6296', '199', '588');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('126', 'Licht', 'OptiWave X1', '6950', '85', '787');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('127', 'Licht', 'MagniCore T5', '2271', '154', '568');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('128', 'Zäune & Absperrungen', 'OmniCore 600', '7380', '117', '787');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('129', 'Zäune & Absperrungen', 'HexaSync 1000', '8989', '173', '320');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('130', 'Zäune & Absperrungen', 'VertexTech 300', '3815', '76', '608');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('131', 'Zäune & Absperrungen', 'VelocityDrive X3', '2046', '47', '820');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('132', 'Stromerzeugung & Verteilung', 'HyperVolt Z3', '5460', '94', '774');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('133', 'Licht', 'OptiFlow 150', '4491', '66', '847');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('134', 'Stromerzeugung & Verteilung', 'HexaVolt X6', '3312', '27', '248');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('135', 'Zäune & Absperrungen', 'VelocityCore 100', '7208', '127', '816');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('136', 'Schall', 'Magnetron 6000', '4045', '46', '350');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('137', 'Schall', 'InfraTech 900', '2201', '175', '405');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('138', 'Zäune & Absperrungen', 'AlphaCore V7', '8778', '176', '669');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('139', 'Überdachung', 'ProEdge V2', '9219', '138', '306');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('140', 'Zäune & Absperrungen', 'NanoPulse T4', '9917', '143', '394');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('141', 'Stromerzeugung & Verteilung', 'HyperCore V1', '4871', '129', '944');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('142', 'Schall', 'InfraCore 500', '4020', '147', '530');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('143', 'Stromerzeugung & Verteilung', 'NeonCore 300', '4478', '45', '469');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('144', 'Pyrotechnik', 'AlphaSeries X200', '1203', '193', '146');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('145', 'Stromerzeugung & Verteilung', 'OmniTrack X1', '4546', '159', '171');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('146', 'Schall', 'NeuroTech X8', '2637', '138', '572');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('147', 'Überdachung', 'DeltaPrime X1', '9348', '136', '110');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('148', 'Instrumente', 'EcoVolt X2', '4717', '23', '657');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('149', 'Licht', 'ZenithPulse X6', '1072', '143', '140');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('150', 'Überdachung', 'StratoPulse X9', '9233', '101', '695');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('151', 'Bühne', 'NeuroPulse Z4', '1174', '144', '651');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('152', 'Zäune & Absperrungen', 'UltraCore 1000', '5718', '171', '152');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('153', 'Bühne', 'SyncCore 800', '4251', '106', '905');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('154', 'Licht', 'UltraPulse X4', '4533', '47', '667');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('155', 'Stromerzeugung & Verteilung', 'EcoFlex X7', '7002', '76', '497');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('156', 'Schall', 'OptiMax 250', '6367', '34', '931');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('157', 'Sonstiges', 'HexaTech 5000', '3501', '150', '503');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('158', 'Überdachung', 'ProtoDrive 700', '3348', '124', '790');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('159', 'Instrumente', 'AlphaEdge V5', '9378', '144', '876');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('160', 'Überdachung', 'OptiDrive X3', '7921', '126', '700');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('161', 'Schall', 'StratoWave X2', '4888', '185', '322');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('162', 'Zäune & Absperrungen', 'NeuroSync X7', '2589', '185', '849');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('163', 'Überdachung', 'TechTrack Z6', '3454', '68', '117');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('164', 'Überdachung', 'TechWave V2', '399', '172', '306');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('165', 'Überdachung', 'InfraCore T7', '2237', '113', '450');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('166', 'Schall', 'VertexCore R2', '8398', '163', '995');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('167', 'Licht', 'EcoPulse X5', '8235', '191', '886');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('168', 'Stromerzeugung & Verteilung', 'NeuroMax 900', '5597', '81', '574');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('169', 'Stromerzeugung & Verteilung', 'QuantumVolt X7', '5415', '95', '446');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('170', 'Pyrotechnik', 'UltraDrive 800', '4672', '86', '959');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('171', 'Überdachung', 'OptiLink 200', '6750', '171', '709');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('172', 'Zäune & Absperrungen', 'NeonGear T2', '3265', '178', '660');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('173', 'Instrumente', 'VelocityTech V3', '7540', '100', '614');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('174', 'Schall', 'TechPulse Z6', '9976', '161', '189');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('175', 'Schall', 'TechPulse Z6', '2657', '104', '900');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('176', 'Zäune & Absperrungen', 'InfraVolt X4', '8027', '52', '651');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('177', 'Instrumente', 'InfraCore T7', '2247', '96', '453');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('178', 'Stromerzeugung & Verteilung', 'OmegaPulse V2', '7321', '110', '146');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('179', 'Schall', 'UltraDrive 800', '8317', '115', '311');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('180', 'Zäune & Absperrungen', 'NeonPulse Z7', '7830', '69', '380');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('181', 'Stromerzeugung & Verteilung', 'OptiMax 250', '4823', '193', '206');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('182', 'Überdachung', 'HexaTech 5000', '5822', '67', '576');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('183', 'Licht', 'NeuroSync X7', '7329', '141', '828');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('184', 'Schall', 'NeuroMax 900', '1710', '22', '825');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('185', 'Schall', 'NeuroWave Z1', '8193', '97', '181');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('186', 'Zäune & Absperrungen', 'TechVolt 500', '2180', '196', '109');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('187', 'Stromerzeugung & Verteilung', 'PowerTrack T2', '495', '185', '340');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('188', 'Zäune & Absperrungen', 'VectorGear 2000', '1684', '151', '260');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('189', 'Überdachung', 'DeltaPrime X1', '7038', '182', '990');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('190', 'Bühne', 'TechWave V2', '1060', '198', '501');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('191', 'Schall', 'PowerTech Z5', '3647', '127', '331');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('192', 'Zäune & Absperrungen', 'MagniFlow 9000', '8913', '66', '713');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('193', 'Bühne', 'MagniDrive X4', '707', '27', '393');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('194', 'Überdachung', 'QuantumCore R4', '6939', '128', '174');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('195', 'Schall', 'NeuroWave Z1', '2922', '87', '322');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('196', 'Instrumente', 'ProtoLink 800', '1586', '135', '695');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('197', 'Zäune & Absperrungen', 'EcoSync 700', '2115', '50', '119');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('198', 'Licht', 'OmegaPulse V2', '6917', '35', '244');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('199', 'Zäune & Absperrungen', 'DeltaPrime X1', '412', '183', '288');
INSERT INTO TECHNIK (technik_id, kategorie, modell, kosten, betriebskosten_std, mietkosten_tag) VALUES ('200', 'Überdachung', 'HyperNet Z10', '6027', '147', '341');
